baseURL = "https://interestinginfosec.gnew.me/"
languageCode = "en-us"
title = "Interest In Infosec"
copyright = "©2020"
theme = "m10c"
paginate = 5

[params]
  author = "Curtis Agnew"
  description = "A repository of projects and adventures. Need to reach me?"
  avatar = "/img/avatar.png"

[[params.about]]
  url = "/about/"

[[params.social]]
  name = "github"
  url = "https://github.com/thesilversverker/"
  
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/silversverker/"

[[params.social]]
  name = "reddit"
  url = "https://reddit.com/u/thesilversverker"  

[[params.social]]
  name = "linkedin"
  url = "https://linkedin.com/curtis.agnew"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
